[package]
name = "ipfs-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cid = "0.11.1"
multihash ="0.19.3"
multicodec = "0.1.0" 
serde = "1.0.200"
tokio = {version = "1.37.0" , features = ["full"]}
